### PR TITLE
Upstream merge v2.60.6

### PR DESCRIPTION
**Pull request by boyuan-chen**
This updates our erigon to the latest upstream release.

### CODE REVIEW

**Review by mmontour1306 — APPROVED** [review]
Note that this will break the current Hybrid Compute bundler (changes the StateDiff datatype from U256 to H256), so we should plan to update both services together on Sepolia.

**Review by jyellick — APPROVED** [review]
Overally LGTM, one small request, could you please update the fork.yaml file to reference the current upstream commit?

**Comment by boyuan-chen** [comment]
> Overally LGTM, one small request, could you please update the fork.yaml file to reference the current upstream commit?

Yes, updated!

**Comment by boyuan-chen** [comment]
> Note that this will break the current Hybrid Compute bundler (changes the StateDiff datatype from U256 to H256), so we should plan to update both services together on Sepolia.

I will do a new release deployment tomorrow. Could you please update the HC image?

**Pull request merged**
