### PR TITLE
Update CI for boba-develop branch

### PR DESCRIPTION
**Pull request by boyuan-chen**
Add CI tests for any PRs to `boba-develop` branch

### CODE REVIEW

**Comment by boyuan-chen** [comment]
The lint issue will be fixed in this PR: https://github.com/bobanetwork/v3-erigon/pull/31

**Comment by boyuan-chen** [comment]
> The lint issue will be fixed in this PR: #31

Fixed here too

**Comment by mmontour1306** [comment]
It looks OK to me but I haven't worked much with CI. If Jason approves it I will do the same.

**Review by jyellick — APPROVED** [review]
LGTM

**Review by mmontour1306 — APPROVED** [review]

**Pull request merged**
