### PR TITLE
Increase the proof range to 2M

### PR DESCRIPTION
**Pull request by boyuan-chen**
This PR increases our `eth_getProof` range to 2M. A more appropriate approach would be to set this variable via the command line as an environment variable, rather than having it as a constant in the codebase.

### CODE REVIEW

**Comment by InoMurko** [comment]
lets monitor the containers memory and CPU consumption

**Review by InoMurko — APPROVED** [review]

**Review by jyellick — APPROVED** [review]
Didn't we have a PR at one point which made this configurable?

Also, this seems like a pretty viable DoS vector -- are we securing this endpoint or at least this call in our deployment?

**Comment by boyuan-chen** [comment]
> Didn't we have a PR at one point which made this configurable?
> 
> Also, this seems like a pretty viable DoS vector -- are we securing this endpoint or at least this call in our deployment?

The PR is closed. https://github.com/bobanetwork/v3-erigon/pull/39/files
This is a temporary fix for our devnet.

**Comment by InoMurko** [comment]
> Didn't we have a PR at one point which made this configurable?
> 
> Also, this seems like a pretty viable DoS vector -- are we securing this endpoint or at least this call in our deployment?

Important point. We should definitely consider 
1. routing these calls to Infra (like Tenderly)
2. routing these calls to Geth
3. dissecting requests within proxyd and restrict calls that are too deep coming from "outside"

**Comment by InoMurko** [comment]
> > Didn't we have a PR at one point which made this configurable?
> > Also, this seems like a pretty viable DoS vector -- are we securing this endpoint or at least this call in our deployment?
> 
> The PR is closed. https://github.com/bobanetwork/v3-erigon/pull/39/files This is a temporary fix for our devnet.

I'll fix that PR attempt.

Tracking DOS here: https://github.com/orgs/bobanetwork/projects/11?pane=issue&itemId=41748172

**Pull request merged**
